/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author mateus
 */
public class TelaEstados extends javax.swing.JFrame {

    /**
     * Creates new form TelaEstados
     */
    public TelaEstados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAberturaEstado = new javax.swing.JTextField();
        txtNomeEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelEditarEstado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEditarDados = new javax.swing.JButton();
        txtNovoNomeEstado = new javax.swing.JTextField();
        txtEditarAbreviatura = new javax.swing.JTextField();
        txtEditarNome = new javax.swing.JTextField();
        txtNovaAbreviatura = new javax.swing.JTextField();
        txtEstadoCadastrado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Insira os dados Abaixo:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 190, 30);

        btnInserir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnInserir.setText(" INSERIR");
        btnInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnInserir);
        btnInserir.setBounds(340, 80, 290, 31);

        btnEditar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditar.setText("EDITAR UM ESTADO");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(340, 120, 290, 31);

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_remove_bin_icon-icons.com_72400.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR UM ESTADO");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(340, 40, 290, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome do Estado:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 108, 17);
        getContentPane().add(txtAberturaEstado);
        txtAberturaEstado.setBounds(160, 120, 130, 31);
        getContentPane().add(txtNomeEstado);
        txtNomeEstado.setBounds(160, 160, 130, 31);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Abreviatura do Estado:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(8, 130, 150, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Você Deseja:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 10, 130, 30);

        panelEditarEstado.setVisible(false);
        panelEditarEstado.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Insira os Dados:");
        panelEditarEstado.add(jLabel6);
        jLabel6.setBounds(20, 30, 160, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Abreviatura  anterior do Estado:");
        panelEditarEstado.add(jLabel5);
        jLabel5.setBounds(10, 90, 180, 15);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Nome anterior do Estado:");
        panelEditarEstado.add(jLabel7);
        jLabel7.setBounds(20, 120, 160, 15);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Nova Abreviatura:");
        panelEditarEstado.add(jLabel8);
        jLabel8.setBounds(20, 150, 150, 15);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Novo Nome do Estado:");
        panelEditarEstado.add(jLabel9);
        jLabel9.setBounds(20, 180, 140, 15);

        btnEditarDados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarDados.setText("EDITAR");
        btnEditarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEditarEstado.add(btnEditarDados);
        btnEditarDados.setBounds(20, 220, 120, 25);
        panelEditarEstado.add(txtNovoNomeEstado);
        txtNovoNomeEstado.setBounds(210, 180, 90, 20);
        panelEditarEstado.add(txtEditarAbreviatura);
        txtEditarAbreviatura.setBounds(210, 90, 90, 20);
        panelEditarEstado.add(txtEditarNome);
        txtEditarNome.setBounds(210, 120, 90, 20);
        panelEditarEstado.add(txtNovaAbreviatura);
        txtNovaAbreviatura.setBounds(210, 150, 90, 20);

        getContentPane().add(panelEditarEstado);
        panelEditarEstado.setBounds(340, 160, 360, 300);
        getContentPane().add(txtEstadoCadastrado);
        txtEstadoCadastrado.setBounds(20, 270, 290, 160);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Estados Já cadastrados: ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 240, 180, 17);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        panelEditarEstado.setVisible(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEstados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarDados;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelEditarEstado;
    private javax.swing.JTextField txtAberturaEstado;
    private javax.swing.JTextField txtEditarAbreviatura;
    private javax.swing.JTextField txtEditarNome;
    private javax.swing.JTextField txtEstadoCadastrado;
    private javax.swing.JTextField txtNomeEstado;
    private javax.swing.JTextField txtNovaAbreviatura;
    private javax.swing.JTextField txtNovoNomeEstado;
    // End of variables declaration//GEN-END:variables
}
