/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mateus
 */
public class TelaVeiculos extends javax.swing.JFrame {

    /**
     * Creates new form TelaVeiculos
     */
    public TelaVeiculos() {
        initComponents();
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnvoltar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarVeiculo = new javax.swing.JButton();
        btnEditarVeiculo = new javax.swing.JButton();
        txtAbreviaturaEstado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmodeloVeiculo = new javax.swing.JTextField();
        btnInserirVeiculo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmarcaVeiculo = new javax.swing.JTextField();
        txtprecoVeiculo = new javax.swing.JTextField();
        txtlojaVeiculo = new javax.swing.JTextField();
        txtPlacaVeiculo = new javax.swing.JTextField();
        txtAnoVeiculo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculo = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        setResizable(false);

        jPanel1.setLayout(null);

        btnvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic-back_97586.png"))); // NOI18N
        btnvoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnvoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvoltarMouseClicked(evt);
            }
        });
        jPanel1.add(btnvoltar);
        btnvoltar.setBounds(22, 10, 60, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Insira os dados Abaixo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 50, 190, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Você Deseja:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(480, 10, 130, 30);

        btnEliminarVeiculo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminarVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete_remove_bin_icon-icons.com_72400.png"))); // NOI18N
        btnEliminarVeiculo.setText("ELIMINAR UM VEICULO");
        btnEliminarVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarVeiculo);
        btnEliminarVeiculo.setBounds(400, 40, 290, 30);

        btnEditarVeiculo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEditarVeiculo.setText("EDITAR UM VEÍCULO");
        btnEditarVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarVeiculo);
        btnEditarVeiculo.setBounds(400, 100, 290, 38);

        txtAbreviaturaEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtAbreviaturaEstado);
        txtAbreviaturaEstado.setBounds(180, 340, 130, 31);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Loja:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 220, 50, 30);

        txtmodeloVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtmodeloVeiculo);
        txtmodeloVeiculo.setBounds(180, 260, 130, 31);

        btnInserirVeiculo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnInserirVeiculo.setText(" INSERIR");
        btnInserirVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInserirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInserirVeiculo);
        btnInserirVeiculo.setBounds(30, 390, 280, 38);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Veículos Já cadastrados: ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 450, 180, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Marca:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 150, 43, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Modelo:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 260, 50, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Preço:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 190, 41, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Placa:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 110, 39, 30);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Ano:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(30, 300, 29, 30);

        txtmarcaVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtmarcaVeiculo);
        txtmarcaVeiculo.setBounds(180, 140, 130, 31);

        txtprecoVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtprecoVeiculo);
        txtprecoVeiculo.setBounds(180, 180, 130, 31);

        txtlojaVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtlojaVeiculo);
        txtlojaVeiculo.setBounds(180, 220, 130, 31);

        txtPlacaVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtPlacaVeiculo);
        txtPlacaVeiculo.setBounds(180, 100, 130, 31);

        txtAnoVeiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtAnoVeiculo);
        txtAnoVeiculo.setBounds(180, 300, 130, 31);

        tabelaVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PLACA", "MARCA", "PREÇO", "LOJA", "MODELO", "ANO", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tabelaVeiculo);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 480, 453, 402);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Abreviatura do Estado:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 350, 150, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvoltarMouseClicked
        // TODO add your handling code here:
        TelaPrincipal telap = new TelaPrincipal();
        this.dispose();
        telap.setVisible(true);
    }//GEN-LAST:event_btnvoltarMouseClicked

    private void btnEliminarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVeiculoActionPerformed
        // TODO add your handling code here:

        if(txtPlacaVeiculo.getText().equals("")|| txtAbreviaturaEstado == null){
            JOptionPane.showMessageDialog(null, "Para remover um Veículo é necessário inserir a placa ao lado.");
        }

        //adicionar a logica para excluir um estado
    }//GEN-LAST:event_btnEliminarVeiculoActionPerformed

    private void btnEditarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVeiculoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnEditarVeiculoActionPerformed

    private void btnInserirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirVeiculoActionPerformed
        // TODO add your handling code here:
        txtmodeloVeiculo.setText("");
        txtmarcaVeiculo.setText("");
        txtprecoVeiculo.setText("");
        txtlojaVeiculo.setText("");
        txtPlacaVeiculo.setText("");
        txtAnoVeiculo.setText("");
        txtAbreviaturaEstado.setText("");
        
        txtPlacaVeiculo.requestFocus();
        if(txtPlacaVeiculo.getText().equals("")|| txtPlacaVeiculo== null || txtmodeloVeiculo.getText().equals("") || txtmodeloVeiculo == null ||
           txtmarcaVeiculo.getText().equals("")|| txtmarcaVeiculo == null|| txtprecoVeiculo.getText().equals("") || txtprecoVeiculo == null ||
           txtlojaVeiculo.getText().equals("") || txtlojaVeiculo==null || txtAnoVeiculo.getText().equals("") || txtAnoVeiculo ==null||
           txtAbreviaturaEstado.getText().equals("")|| txtAbreviaturaEstado==null){
            JOptionPane.showMessageDialog(null, "Para Adicioanr um Veículo é necessário inserir os dados acima.");

        }
        if(!(txtPlacaVeiculo.getText().equals("")|| txtPlacaVeiculo== null || txtmodeloVeiculo.getText().equals("") || txtmodeloVeiculo == null ||
           txtmarcaVeiculo.getText().equals("")|| txtmarcaVeiculo == null|| txtprecoVeiculo.getText().equals("") || txtprecoVeiculo == null ||
           txtlojaVeiculo.getText().equals("") || txtlojaVeiculo==null || txtAnoVeiculo.getText().equals("") || txtAnoVeiculo ==null||
           txtAbreviaturaEstado.getText().equals("")|| txtAbreviaturaEstado==null)){
            JOptionPane.showMessageDialog(null, "Estado Adicionado");
            //adicionar a logica para adicionar um estado

            
        }

    }//GEN-LAST:event_btnInserirVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarVeiculo;
    private javax.swing.JButton btnEliminarVeiculo;
    private javax.swing.JButton btnInserirVeiculo;
    private javax.swing.JLabel btnvoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVeiculo;
    private javax.swing.JTextField txtAbreviaturaEstado;
    private javax.swing.JTextField txtAnoVeiculo;
    private javax.swing.JTextField txtPlacaVeiculo;
    private javax.swing.JTextField txtlojaVeiculo;
    private javax.swing.JTextField txtmarcaVeiculo;
    private javax.swing.JTextField txtmodeloVeiculo;
    private javax.swing.JTextField txtprecoVeiculo;
    // End of variables declaration//GEN-END:variables
}
