/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import javax.swing.JOptionPane;

/**
 *
 * @author mateus
 */
public class TelaConsultar extends javax.swing.JFrame {


    /**
     * Creates new form TelaConsultar
     */
    public TelaConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnvoltar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelPlaca = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtconsultplaca = new javax.swing.JTextField();
        btnconsultplaca = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabelaPlaca = new javax.swing.JTable();
        consultaPlaca = new javax.swing.JButton();
        consultaPreco = new javax.swing.JButton();
        consultaMarca = new javax.swing.JButton();
        consultaModelo = new javax.swing.JButton();
        panelMarca = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtconsultamarca = new javax.swing.JTextField();
        btnconsultamarca = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaMarca = new javax.swing.JTable();
        panelModelo = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtconsultamodelo = new javax.swing.JTextField();
        btnconsultamodelo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaModelo = new javax.swing.JTable();
        panelPreco = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtconsultapreco = new javax.swing.JTextField();
        btnconsultapreco = new javax.swing.JButton();
        txtconsultapreco2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPreco = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1583, 780));
        getContentPane().setLayout(null);

        btnvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic-back_97586.png"))); // NOI18N
        btnvoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnvoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvoltarMouseClicked(evt);
            }
        });
        getContentPane().add(btnvoltar);
        btnvoltar.setBounds(20, 10, 60, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTAR POR:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 230, 20);

        panelPlaca.setVisible(false);
        panelPlaca.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Por favor digite a placa para consultar");
        panelPlaca.add(jLabel7);
        jLabel7.setBounds(19, 11, 310, 25);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Informações encontradas");
        panelPlaca.add(jLabel8);
        jLabel8.setBounds(190, 80, 170, 17);

        txtconsultplaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelPlaca.add(txtconsultplaca);
        txtconsultplaca.setBounds(30, 50, 120, 20);

        btnconsultplaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnconsultplaca.setText("CONSULTAR");
        btnconsultplaca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnconsultplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultplacaActionPerformed(evt);
            }
        });
        panelPlaca.add(btnconsultplaca);
        btnconsultplaca.setBounds(30, 80, 110, 31);

        tabelaPlaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MODELO", "MARCA", "PREÇO", "LOJA", "PLACA", "ANO", "ESTADO"
            }
        ));
        jScrollPane9.setViewportView(tabelaPlaca);

        panelPlaca.add(jScrollPane9);
        jScrollPane9.setBounds(70, 110, 370, 130);

        getContentPane().add(panelPlaca);
        panelPlaca.setBounds(340, 60, 440, 240);

        consultaPlaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultaPlaca.setText("PLACA");
        consultaPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consultaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(consultaPlaca);
        consultaPlaca.setBounds(240, 150, 90, 33);

        consultaPreco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultaPreco.setText("PREÇO");
        consultaPreco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consultaPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaPrecoActionPerformed(evt);
            }
        });
        getContentPane().add(consultaPreco);
        consultaPreco.setBounds(950, 510, 100, 33);

        consultaMarca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultaMarca.setText("MARCA");
        consultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(consultaMarca);
        consultaMarca.setBounds(960, 170, 90, 33);

        consultaModelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        consultaModelo.setText("MODELO");
        consultaModelo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        consultaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaModeloActionPerformed(evt);
            }
        });
        getContentPane().add(consultaModelo);
        consultaModelo.setBounds(240, 480, 100, 33);

        panelMarca.setVisible(false);
        panelMarca.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Por favor digite a marca para consultar");
        panelMarca.add(jLabel13);
        jLabel13.setBounds(19, 11, 310, 25);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Informações encontradas");
        panelMarca.add(jLabel14);
        jLabel14.setBounds(190, 80, 170, 17);

        txtconsultamarca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelMarca.add(txtconsultamarca);
        txtconsultamarca.setBounds(30, 50, 120, 20);

        btnconsultamarca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnconsultamarca.setText("CONSULTAR");
        btnconsultamarca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnconsultamarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultamarcaActionPerformed(evt);
            }
        });
        panelMarca.add(btnconsultamarca);
        btnconsultamarca.setBounds(30, 80, 110, 31);

        tabelaMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MODELO", "MARCA", "PREÇO", "LOJA", "PLACA", "ANO", "ESTADO"
            }
        ));
        jScrollPane4.setViewportView(tabelaMarca);

        panelMarca.add(jScrollPane4);
        jScrollPane4.setBounds(70, 110, 370, 130);

        getContentPane().add(panelMarca);
        panelMarca.setBounds(1060, 80, 450, 240);

        panelModelo.setVisible(false);
        panelModelo.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Por favor digite o modelo para consultar");
        panelModelo.add(jLabel15);
        jLabel15.setBounds(19, 11, 330, 25);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Informações encontradas");
        panelModelo.add(jLabel16);
        jLabel16.setBounds(190, 80, 170, 17);

        txtconsultamodelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelModelo.add(txtconsultamodelo);
        txtconsultamodelo.setBounds(30, 50, 120, 20);

        btnconsultamodelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnconsultamodelo.setText("CONSULTAR");
        btnconsultamodelo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnconsultamodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultamodeloActionPerformed(evt);
            }
        });
        panelModelo.add(btnconsultamodelo);
        btnconsultamodelo.setBounds(30, 80, 110, 31);

        tabelaModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MODELO", "MARCA", "PREÇO", "LOJA", "PLACA", "ANO", "ESTADO"
            }
        ));
        jScrollPane5.setViewportView(tabelaModelo);

        panelModelo.add(jScrollPane5);
        jScrollPane5.setBounds(80, 110, 370, 130);

        getContentPane().add(panelModelo);
        panelModelo.setBounds(340, 390, 450, 240);

        panelPreco.setVisible(false);
        panelPreco.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setText("Por favor digite o preço inicial e final para consultar");
        panelPreco.add(jLabel17);
        jLabel17.setBounds(19, 11, 420, 25);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Informações encontradas");
        panelPreco.add(jLabel18);
        jLabel18.setBounds(190, 80, 170, 17);

        txtconsultapreco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        panelPreco.add(txtconsultapreco);
        txtconsultapreco.setBounds(30, 50, 120, 20);

        btnconsultapreco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnconsultapreco.setText("CONSULTAR");
        btnconsultapreco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnconsultapreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultaprecoActionPerformed(evt);
            }
        });
        panelPreco.add(btnconsultapreco);
        btnconsultapreco.setBounds(30, 110, 110, 31);
        panelPreco.add(txtconsultapreco2);
        txtconsultapreco2.setBounds(30, 80, 120, 24);

        tabelaPreco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MODELO", "MARCA", "PREÇO", "LOJA", "PLACA", "ANO", "ESTADO"
            }
        ));
        jScrollPane3.setViewportView(tabelaPreco);

        panelPreco.add(jScrollPane3);
        jScrollPane3.setBounds(80, 140, 440, 160);

        getContentPane().add(panelPreco);
        panelPreco.setBounds(1060, 420, 520, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvoltarMouseClicked
        // TODO add your handling code here:
        TelaPrincipal telap = new TelaPrincipal();
        this.dispose();
        telap.setVisible(true);
    }//GEN-LAST:event_btnvoltarMouseClicked

    private void consultaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPlacaActionPerformed
        // TODO add your handling code here:
        
        panelPlaca.setVisible(true);
    }//GEN-LAST:event_consultaPlacaActionPerformed

    private void consultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMarcaActionPerformed
        // TODO add your handling code here:
        
        panelMarca.setVisible(true);
    }//GEN-LAST:event_consultaMarcaActionPerformed

    private void consultaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaModeloActionPerformed
        // TODO add your handling code here:
        panelModelo.setVisible(true);
    }//GEN-LAST:event_consultaModeloActionPerformed

    private void consultaPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaPrecoActionPerformed
        // TODO add your handling code here:
        panelPreco.setVisible(true);
    }//GEN-LAST:event_consultaPrecoActionPerformed

    private void btnconsultplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultplacaActionPerformed
        // TODO add your handling code here:
        
        if(txtconsultplaca.getText().equals("") || txtconsultplaca==null){
            JOptionPane.showMessageDialog(null, "Placa não encontrada ou inexistente. Verifique se foi digitado corretamente");
        }
        
    }//GEN-LAST:event_btnconsultplacaActionPerformed

    private void btnconsultamodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultamodeloActionPerformed
        // TODO add your handling code here:
         if(txtconsultamodelo.getText().equals("") || txtconsultamodelo==null){
            JOptionPane.showMessageDialog(null, "Modelo não encontrado ou inexistente. Verifique se foi digitado corretamente");
        }
    }//GEN-LAST:event_btnconsultamodeloActionPerformed

    private void btnconsultamarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultamarcaActionPerformed
        // TODO add your handling code here:
        if(txtconsultamarca.getText().equals("") || txtconsultamarca==null){
            JOptionPane.showMessageDialog(null, "Marca não encontrada ou inexistente. Verifique se foi digitado corretamente");
        }
    }//GEN-LAST:event_btnconsultamarcaActionPerformed

    private void btnconsultaprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultaprecoActionPerformed
        // TODO add your handling code here:
        if(txtconsultapreco.getText().equals("") || txtconsultapreco==null || txtconsultapreco2.getText().equals("") || txtconsultapreco2==null){
            JOptionPane.showMessageDialog(null, "Não foi possível encontrar nessa faixetaria. digite novamente");
        }
    }//GEN-LAST:event_btnconsultaprecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultamarca;
    private javax.swing.JButton btnconsultamodelo;
    private javax.swing.JButton btnconsultapreco;
    private javax.swing.JButton btnconsultplaca;
    private javax.swing.JLabel btnvoltar;
    private javax.swing.JButton consultaMarca;
    private javax.swing.JButton consultaModelo;
    private javax.swing.JButton consultaPlaca;
    private javax.swing.JButton consultaPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel panelMarca;
    private javax.swing.JPanel panelModelo;
    private javax.swing.JPanel panelPlaca;
    private javax.swing.JPanel panelPreco;
    private javax.swing.JTable tabelaMarca;
    private javax.swing.JTable tabelaModelo;
    private javax.swing.JTable tabelaPlaca;
    private javax.swing.JTable tabelaPreco;
    private javax.swing.JTextField txtconsultamarca;
    private javax.swing.JTextField txtconsultamodelo;
    private javax.swing.JTextField txtconsultapreco;
    private javax.swing.JTextField txtconsultapreco2;
    private javax.swing.JTextField txtconsultplaca;
    // End of variables declaration//GEN-END:variables
}
